### ISSUE TITLE
Toggling GodMode doesn't keep input focus consistency

### ISSUE THREAD

**Issue by 0xAsynchronous** [smol-ai/GodMode#221]
**Description:** Toggling GodMode doesn't keep input focus consistency. I often will edit things in subprompts because I want to use a certain LLM for a certain task without triggering all of them (i.e. I will use one LLM for writing and another for code, depending on which one performs better in each task). When writing these LLM-specific prompts, I often quickly tab out to check or copy something in my code editor or the web and (because my input focus get changed on me) always accidentally paste into the superprompt which completely demolishes the prompt I have been crafting in the subprompt box. Additionally, because there is no undo history in the subprompt boxes, I am forced to rewrite the prompt all over again from memory.

**Steps to Reproduce:**
1) Launch GodMode
2) Type into a sub-prompt (i.e. chatGPT)
3) Toggle with universal shortcut (hide)
4) Toggle with universal shortcut (show)

**Expected behavior:** Will put your cursor into the last used input box before toggle.
**Actual behavior:** Focus is always returned to the superprompt input.

**Environment:** macOS 13.4. GodMode (1.0.0-beta.0)

**Comment by swyxio** [comment]
yikes sorry about that. i hear you, i dont do much in subprompts but i see how this could be annoying. we actually ADD code to make this prompt behavior happen because some people like it, 

https://github.com/smol-ai/GodMode/blob/09b4767fd8473ef43d9b288d972042534f775c90/src/main/main.ts#L369

but i could see taking an option to turn this behavior off. theres a bigger longer term solve where the "quick llm" usecase is addressed by @seanoliver's "raycast app UX"  we have talked about internally but for now we should just take an option to disable superprompt focusing.
