### ISSUE TITLE
[Bug] ChatGPT keep asking me to 'verify human' everytime

### ISSUE THREAD

**Issue by karpedm** [smol-ai/GodMode#243]
My ChatGPT doesn't think I'm a human. it keep verifying me.

(I managed to auth Bard by copying cookies from normal browse. can this be the reason?)

**Comment by lgandecki** [comment]
I didn't copy the cookies and I have the same problem. The verifications take way too much time to be reasonable. In that time it is much faster to just copy and paste the query into a browser.

To be honest I pretty much stopped using this because perplexity doesn't work, chatgpt is unusuable, and those were usually the best two options.  Inflection PI doesn't work neither anymore and I liked it short and more human-like answers. Sad. This project is such a great idea. 

I could probably fix Inflection PI, there is Perplexity PR waiting to be merged, supposedly fixing the loop, but not sure what to do about the ChatGPT. All in all it seems long term this might be a constant struggle to keep up with the providers, not sure if there is enough community drive behind this project to keep up with that. :-(

**Comment by karpedm** [comment]
I really love this app. This was exactly what I was searching for.
Please someone rescue us ~  without chatGPT, ...

**Comment by PhillipRt** [comment]
We sould take a look into what superpower chatgpt did. Is an open source extention thst ran into bot prevention aswell but reverse engineered the whole bot prevention. Also the maintainer is very active on discord so he might even give advice

**Comment by swyxio** [comment]
@PhillipRt @lgandecki @karpedm  hey guys, sorry i fell behind on fixing the issues - it was just an outdated user agent string. i've fixed that in #258 and we will be releasing as beta.9! pls reopen if any further issues.

**Comment by PhillipRt** [comment]
@swyxio fix probability was not even needed, the founder mentioned that they had some cloudflare issues generally https://twitter.com/AravSrinivas/status/1708537032769933512

Thank you for your work, definitely future profs the software and makes bans less likely

**Comment by swyxio** [comment]
ahh lol.
