### ISSUE TITLE
Peplexity AI Not Working

### ISSUE THREAD

**Issue by LiatHa** [smol-ai/GodMode#249]
**Describe the bug**
Perplexity AI Checking if the site connection is secure forever and not loading because of that.

**To Reproduce**
Open the godmode app (btw, no start menu shortcut available using the exe installation. which means redoing the setup over and over again).
Add the provider of perplexity AI
![image](https://github.com/smol-ai/GodMode/assets/141867404/45519bcd-caf1-4c34-96c8-df44576abf26)

**Expected behavior**
Open the perplexity AI login page

**Screenshots**
![image](https://github.com/smol-ai/GodMode/assets/141867404/4f3a3f39-5478-47f9-9c3c-3f4716d83f6e)
**Desktop (please complete the following information):**

- OS: Windows 11
- GodMode Version  - v1 beta 8

**Additional context**

**Comment by MarshallkHeadline** [comment]
Additional note: this behavior results in a focus stealing loop, too, so you can't ignore it.

**Comment by MarshallkHeadline** [comment]
Note: this also results in a focus stealing loop, so you can't ignore it and use other apps.  Requires Perplexity (and Llama 2 in Perplexity) to be removed.

**Comment by PhillipRt** [comment]
I think perplexity went overboard with the bot detection. I even get issues like this using it in the normal browser. You can track the request in the dev console to cloudflare and it comes back with bot again and again. I think you have to allow any traffic, no adblock or pihole and have a clean user agent. Also do not use a vpn, because it will make it look like a lot of requests are coming from it. Might be worth looking into puppeteer and puppeteer stealth to determine what works and what doesn't.
Also a lot of the unofficial apis should have the same problem, maybe we can ask in those repos if they found a solution.

So i would say, things try:
- chnage the user agent to a popular browser, make sure that the godmode browser looks exactly the same as chrome, edge, safari
- prevent TLS and HTML/2 fingerprinting. Make sure the TLS HTML/2 fingerprint matches with the user agent

Since we are not scraping, this is legal and should not be to difficult.

As a last resort, we could reach out to the team, they seem on the pulse and probably do not have issues with what we are doing. Maybe they will whitelist godmode

Source: https://www.zenrows.com/blog/bypass-cloudflare#cloudflare-solvers

**Comment by swyxio** [comment]
yeah totally - @mwyywm updated user agent in #239 - releasing in beta.9!
